#!/usr/bin/env bash
set -euo pipefail
# v3 — всегда используем sysfs-путь: -p /sys/class/net/$IFACE

UDEV_RULES=0
if [[ "${1:-}" == "--udev" ]]; then UDEV_RULES=1; shift; fi

if [[ $EUID -ne 0 ]]; then
  echo "Запусти от root (sudo)." >&2; exit 1
fi
if [[ $# -lt 1 ]]; then
  echo "Использование: $0 [--udev] enpX=modem1 enpY=modem2 ..." >&2; exit 1
fi

LINK_DIR="/etc/systemd/network"
RULES_DIR="/etc/udev/rules.d"
mkdir -p "$LINK_DIR" "$RULES_DIR"

timestamp="$(date +%Y%m%d-%H%M%S)"
tmp_trigger_list="$(mktemp)"

valid_name() { [[ "$1" =~ ^[a-z0-9_.:-]+$ ]]; }

create_link_file() {
  local new="$1" id_path="$2" driver="$3"
  local f="$LINK_DIR/10-${new}.link"
  cat >"$f" <<EOF
# autogenerated by persist-net-names.sh on $timestamp
[Match]
Path=${id_path}
${driver:+Driver=${driver}}

[Link]
Name=${new}
EOF
  echo "📝 .link: $f"
}

append_udev_rule() {
  local new="$1" id_path="$2" ven="$3" prod="$4"
  local f="$RULES_DIR/70-persist-modems.rules"
  local rule="SUBSYSTEM==\"net\", ACTION==\"add\", ENV{ID_PATH}==\"${id_path}\"${ven:+, ENV{ID_VENDOR_ID}==\"$ven\"}${prod:+, ENV{ID_MODEL_ID}==\"$prod\"}, NAME=\"${new}\""
  if ! grep -Fq "$rule" "$f" 2>/dev/null; then
    echo "$rule" >> "$f"
    echo "📝 udev rule добавлен: $f"
  else
    echo "ℹ️  udev rule уже есть: $f"
  fi
}

for pair in "$@"; do
  [[ "$pair" == *"="* ]] || { echo "❌ Аргумент '$pair' не вида IFACE=NAME"; continue; }
  cur="${pair%%=*}"
  new="${pair#*=}"

  if [[ ! -e "/sys/class/net/$cur" ]]; then
    echo "❌ Интерфейс '$cur' не найден (/sys/class/net/$cur). Пропускаю."
    continue
  fi
  if ! valid_name "$new"; then
    echo "❌ Новое имя '$new' недопустимо (^[a-z0-9_.:-]+$). Пропускаю."
    continue
  fi
  if [[ -e "/sys/class/net/$new" ]]; then
    echo "❌ В системе уже есть интерфейс '$new'. Пропускаю."
    continue
  fi

  sysfs="/sys/class/net/$cur"
  props="$(udevadm info -q property -p "$sysfs")" || props=""

  id_path="$(sed -n 's/^ID_PATH=//p' <<<"$props" | head -n1)"
  driver="$(sed -n 's/^ID_NET_DRIVER=//p' <<<"$props" | head -n1)"
  ven="$(sed -n 's/^ID_VENDOR_ID=//p' <<<"$props" | head -n1)"
  prod="$(sed -n 's/^ID_MODEL_ID=//p' <<<"$props" | head -n1)"
  devpath_full="$(sed -n 's/^DEVPATH=//p' <<<"$props" | head -n1)"

  echo "→ $cur:"
  echo "   sysfs: $sysfs"
  [[ -n "$devpath_full" ]] && echo "   DEVPATH: $devpath_full"
  echo "   ID_PATH: ${id_path:-<none>}"
  echo "   Driver: ${driver:-<none>}"

  if [[ -z "$id_path" ]]; then
    echo "⚠️  ID_PATH не найден (редко, но бывает). Попробуем fallback из udevadm info -a…"
    # Fallback: попытаться вытащить путь родительского USB-интерфейса
    id_path="$(udevadm info -a -p "$sysfs" 2>/dev/null | sed -n 's/^ *ATTRS{devpath}==\"\(.*\)\".*$/\1/p' | head -n1)"
    if [[ -n "$id_path" ]]; then
      echo "   Fallback ID_PATH(candidate): $id_path"
    else
      echo "❌ Не удалось получить стабильный Path для '$cur'. Пропускаю."
      continue
    fi
  fi

  create_link_file "$new" "$id_path" "$driver"
  [[ $UDEV_RULES -eq 1 ]] && append_udev_rule "$new" "$id_path" "$ven" "$prod"

  echo "$sysfs" >> "$tmp_trigger_list"
  echo "✅ ${cur} → ${new}"
done

echo
echo "↻ Перезагружаю правила…"
udevadm control --reload || true
systemctl daemon-reload || true

if [[ -s "$tmp_trigger_list" ]]; then
  while read -r p; do
    [[ -e "$p" ]] || continue
    echo "→ udevadm trigger -c add $p"
    udevadm trigger -c add "$p" || true
  done < "$tmp_trigger_list"
fi

echo
echo "Готово. Если имена не сменились сразу — переподключи модемы или перезагрузи машину."
echo "Файлы: .link в ${LINK_DIR} ${UDEV_RULES:+; udev-правила в ${RULES_DIR}/70-persist-modems.rules}"
